---
name: Build

on:
  workflow_dispatch:
    inputs:
      kernelBranch:
        description: "WSL2-Linux-Kernel branch"
        required: true
        default: "linux-msft-wsl-6.6.y"
        type: string
      build-modules:
        description: "Build modules?"
        required: true
        default: false
        type: boolean
      custom-config:
        description: "Use custom config?"
        required: true
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.kernelBranch }}
  cancel-in-progress: true

permissions:
  id-token: write
  attestations: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    name: "build-${{ inputs.kernelBranch }}"
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout WSL2-Linux-Kernel repository
        uses: actions/checkout@v6
        with:
          repository: microsoft/WSL2-Linux-Kernel
          ref: ${{ github.event.inputs.kernelBranch }}

      - name: Checkout custom-config
        if: ${{ inputs.custom-config }}
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: .config

      - name: Install requirements
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y build-essential flex bison dwarves libssl-dev libelf-dev cpio qemu-utils

      - name: Copy custom config
        id: custom-config
        if: ${{ inputs.custom-config }}
        run: |
          cp .config/config/config-wsl2-docker.cfg arch/x86/configs/config-wsl

      - name: Build WSL2-Linux-Kernel
        id: build-kernel
        run: |
          echo "::group::Build kernel"
          make -j$(nproc) KCONFIG_CONFIG=Microsoft/config-wsl
          echo "::endgroup::"

      - name: Build WSL2-Linux-Kernel modules
        id: build-modules
        if: ${{ inputs.build-modules }}
        run: |
          echo "::group::Build modules"
          if [[ ${{ inputs.kernelBranch }} == "linux-msft-wsl-6.6.y" ]];
          then
            make -j$(nproc) INSTALL_MOD_PATH="$PWD/modules" modules_install
            sudo ./Microsoft/scripts/gen_modules_vhdx.sh "$PWD/modules" $(make -s kernelrelease) arch/x86/boot/modules.vhdx
          else
            touch modules.vhdx
          fi
          echo "::endgroup::"

      - uses: actions/upload-artifact@v5
        id: upload-artifact
        with:
          name: WSL2-Kernel-${{ inputs.kernelBranch }}
          path: |
            arch/x86/boot/bzImage
            arch/x86/boot/modules.vhdx

      - uses: actions/attest-build-provenance@v3
        id: attestations
        with:
          subject-name: WSL2-Kernel-${{ inputs.kernelBranch }}
          subject-digest: sha256:${{ steps.upload-artifact.outputs.artifact-digest }}
